import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define Gilroy font
const gilroy = localFont({
  src: [
    {
      path: '../fonts/Gilroy-Light.ttf',
      weight: '300',
      style: 'normal',
    }
  ],
  variable: '--font-gilroy',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${gilroy.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
